apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base/podinfo
patches:
  - path: helmrelease.yaml
    target:
      kind: HelmRelease
      name: podinfo