# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: testing
# resources:
#   - namespace.yaml
#   - rbac.yaml
#   - sync.yaml
# labels:
#   - pairs:
#       toolkit.fluxcd.io/tenant: home