apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - home-apps.yaml
  - home-infra.yaml
  - sync.yaml
  - sourceauth.yaml
  - rbac.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: home