---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/development/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  targetNamespace: dev
  timeout: 3m0s
  wait: true
