apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  releaseName: flux-operator
  chartRef:
    kind: OCIRepository
    name: flux-operator
  timeout: 3m
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
  interval: 12h
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]