---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: control-plane-controllers
spec:
  serviceAccountName: flux-infra
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/control-plane/controllers/${ENVIRONMENT}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: control-plane-configs
spec:
  serviceAccountName: flux-infra
  dependsOn:
    - name: control-plane-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/control-plane/configs/${ENVIRONMENT}
