---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases-controllers
spec:
  serviceAccountName: flux-infra
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: infra/components/databases/controllers/${ENVIRONMENT}
