apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: definitions
spec:
  serviceAccountName: flux-infra
  interval: 10m
  retryInterval: 2m
  timeout: 20m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: infra/components/definitions
