apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - rbac.yaml
  - source.yaml
  - crds.yaml
  - databases.yaml
  - control-plane.yaml
  - ingress.yaml
  - observability.yaml
  - brokers.yaml
  - security.yaml
  - definitions.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: infra