---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-controllers
spec:
  serviceAccountName: flux-infra
  interval: 1m
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/security/controllers/${ENVIRONMENT}

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-configs
spec:
  serviceAccountName: flux-infra
  dependsOn:
    - name: security-controllers
  interval: 1m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/security/configs/${ENVIRONMENT}