---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-controllers
spec:
  serviceAccountName: flux-infra
  interval: 10m
  retryInterval: 2m
  timeout: 2m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: infra/components/storage/controllers/${ENVIRONMENT}
