apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kro
spec:
  releaseName: kro
  chartRef:
    kind: OCIRepository
    name: kro
    namespace: kube-system
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 10m
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
  values:
    metrics:
      service:
        create: true
      serviceMonitor:
        enabled: true