---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-home-apps
  namespace: flux-system
spec:
  serviceAccountName: flux-home
  dependsOn:
  - name: flux-home-infra
  interval: 10m
  retryInterval: 2m
  timeout: 2m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-home
  path: ./components/apps
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  commonMetadata:
    labels:
      toolkit.fluxcd.io/tenant: home
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          commonMetadata:
            labels:
              toolkit.fluxcd.io/tenant: home
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: flux-runtime-info
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization