---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 1m0s
  values:
    ingress:
      className: traefik
      enabled: true
      hosts:
      - host: podinfo-base.home
        paths:
        - path: /
          pathType: Prefix
