apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: ops
spec:
  interval: 10m
  chart:
    spec:
      chart: bitnami/rabbitmq-cluster-operator
      sourceRef:
        kind: OCIRepository
        name: rabbitmq-operator
        namespace: ops
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
  values: